export default {
  products: [
    {
      _id: "1",
      name: "Pirelli",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Pirelli",
      availability: "Available",
    },

    {
      _id: "2",
      name: "Pirelli",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Pirelli",
      availability: "Available",
    },
    {
      _id: "3",
      name: "Pirelli",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Pirelli",
      availability: "Available",
    },
    {
      _id: "4",
      name: "Pirelli",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Pirelli",
      availability: "Available",
    },
    {
      _id: "5",
      name: "Pirelli",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Pirelli",
      availability: "Available",
    },

    {
      _id: "6",
      name: "Michelin",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Michelin",
      availability: "Available",
    },

    {
      _id: "7",
      name: "Michelin",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Michelin",
      availability: "Available",
    },

    {
      _id: "8",
      name: "Michelin",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Michelin",
      availability: "Available",
    },

    {
      _id: "9",
      name: "Michelin",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Michelin",
      availability: "Available",
    },

    {
      _id: "10",
      name: "Michelin",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Michelin",
      availability: "Available",
    },

    {
      _id: "11",
      name: "Hankook",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Hankook",
      availability: "Available",
    },

    {
      _id: "12",
      name: "Hankook",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Hankook",
      availability: "Available",
    },

    {
      _id: "13",
      name: "Hankook",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Hankook",
      availability: "Available",
    },

    {
      _id: "14",
      name: "Hankook",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Hankook",
      availability: "Available",
    },

    {
      _id: "15",
      name: "Hankook",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Hankook",
      availability: "Available",
    },

    {
      _id: "16",
      name: "Good year",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Good year",
      availability: "Available",
    },

    {
      _id: "17",
      name: "Good year",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Good year",
      availability: "Available",
    },

    {
      _id: "18",
      name: "Good year",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Good year",
      availability: "Available",
    },

    {
      _id: "19",
      name: "Good year",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Good year",
      availability: "Available",
    },

    {
      _id: "20",
      name: "Good year",
      p: "P Zero",
      m: "205/55/R16",
      i: "82 T i",
      category: "Car / Off road vehicles ATV",
      price1: 475.0,
      price2: 475.0,
      brand: "Good year",
      availability: "Available",
    },
  ],
};
